export const API_ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_REQUEST: "INVALID_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DEPENDENCY_FAILURE: "DEPENDENCY_FAILURE",
} as const;

export const {
  NOT_FOUND,
  UNAUTHORIZED,
  FORBIDDEN,
  INVALID_REQUEST,
  INTERNAL_ERROR,
  DEPENDENCY_FAILURE,
} = API_ERROR_CODES;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
